// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/graph.go
//
// Generated by this command:
//
//	mockgen -source=../repository/graph.go -destination=mock_graph_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-graph-authoring/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphRepository is a mock of GraphRepository interface.
type MockGraphRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGraphRepositoryMockRecorder
	isgomock struct{}
}

// MockGraphRepositoryMockRecorder is the mock recorder for MockGraphRepository.
type MockGraphRepositoryMockRecorder struct {
	mock *MockGraphRepository
}

// NewMockGraphRepository creates a new mock instance.
func NewMockGraphRepository(ctrl *gomock.Controller) *MockGraphRepository {
	mock := &MockGraphRepository{ctrl: ctrl}
	mock.recorder = &MockGraphRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphRepository) EXPECT() *MockGraphRepositoryMockRecorder {
	return m.recorder
}

// FindByEventPublicIDForUpdate mocks base method.
func (m *MockGraphRepository) FindByEventPublicIDForUpdate(ctx context.Context, tenantPublicID, eventPublicID string) (domain.VenueGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEventPublicIDForUpdate", ctx, tenantPublicID, eventPublicID)
	ret0, _ := ret[0].(domain.VenueGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEventPublicIDForUpdate indicates an expected call of FindByEventPublicIDForUpdate.
func (mr *MockGraphRepositoryMockRecorder) FindByEventPublicIDForUpdate(ctx, tenantPublicID, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEventPublicIDForUpdate", reflect.TypeOf((*MockGraphRepository)(nil).FindByEventPublicIDForUpdate), ctx, tenantPublicID, eventPublicID)
}

// FindCurrentRevision mocks base method.
func (m *MockGraphRepository) FindCurrentRevision(ctx context.Context, eventPublicID string) (domain.PublishedRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCurrentRevision", ctx, eventPublicID)
	ret0, _ := ret[0].(domain.PublishedRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCurrentRevision indicates an expected call of FindCurrentRevision.
func (mr *MockGraphRepositoryMockRecorder) FindCurrentRevision(ctx, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCurrentRevision", reflect.TypeOf((*MockGraphRepository)(nil).FindCurrentRevision), ctx, eventPublicID)
}

// Publish mocks base method.
func (m *MockGraphRepository) Publish(ctx context.Context, graph domain.VenueGraph) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, graph)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockGraphRepositoryMockRecorder) Publish(ctx, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGraphRepository)(nil).Publish), ctx, graph)
}

// Save mocks base method.
func (m *MockGraphRepository) Save(ctx context.Context, graph domain.VenueGraph) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, graph)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGraphRepositoryMockRecorder) Save(ctx, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGraphRepository)(nil).Save), ctx, graph)
}
