// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/graph.go
//
// Generated by this command:
//
//	mockgen -source=../repository/graph.go -destination=mock_graph_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-graph-authoring/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphRepository is a mock of GraphRepository interface.
type MockGraphRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGraphRepositoryMockRecorder
	isgomock struct{}
}

// MockGraphRepositoryMockRecorder is the mock recorder for MockGraphRepository.
type MockGraphRepositoryMockRecorder struct {
	mock *MockGraphRepository
}

// NewMockGraphRepository creates a new mock instance.
func NewMockGraphRepository(ctrl *gomock.Controller) *MockGraphRepository {
	mock := &MockGraphRepository{ctrl: ctrl}
	mock.recorder = &MockGraphRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphRepository) EXPECT() *MockGraphRepositoryMockRecorder {
	return m.recorder
}

// AddQrLocation mocks base method.
func (m *MockGraphRepository) AddQrLocation(ctx context.Context, graph domain.Graph, location domain.QrLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddQrLocation", ctx, graph, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddQrLocation indicates an expected call of AddQrLocation.
func (mr *MockGraphRepositoryMockRecorder) AddQrLocation(ctx, graph, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddQrLocation", reflect.TypeOf((*MockGraphRepository)(nil).AddQrLocation), ctx, graph, location)
}

// FindByEventPublicID mocks base method.
func (m *MockGraphRepository) FindByEventPublicID(ctx context.Context, tenantPublicID, eventPublicID string) (domain.Graph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEventPublicID", ctx, tenantPublicID, eventPublicID)
	ret0, _ := ret[0].(domain.Graph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEventPublicID indicates an expected call of FindByEventPublicID.
func (mr *MockGraphRepositoryMockRecorder) FindByEventPublicID(ctx, tenantPublicID, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEventPublicID", reflect.TypeOf((*MockGraphRepository)(nil).FindByEventPublicID), ctx, tenantPublicID, eventPublicID)
}

// FindByEventPublicIDForUpdate mocks base method.
func (m *MockGraphRepository) FindByEventPublicIDForUpdate(ctx context.Context, tenantPublicID, eventPublicID string) (domain.Graph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEventPublicIDForUpdate", ctx, tenantPublicID, eventPublicID)
	ret0, _ := ret[0].(domain.Graph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEventPublicIDForUpdate indicates an expected call of FindByEventPublicIDForUpdate.
func (mr *MockGraphRepositoryMockRecorder) FindByEventPublicIDForUpdate(ctx, tenantPublicID, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEventPublicIDForUpdate", reflect.TypeOf((*MockGraphRepository)(nil).FindByEventPublicIDForUpdate), ctx, tenantPublicID, eventPublicID)
}

// FindCurrentRevision mocks base method.
func (m *MockGraphRepository) FindCurrentRevision(ctx context.Context, eventPublicID string) (domain.PublishedRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCurrentRevision", ctx, eventPublicID)
	ret0, _ := ret[0].(domain.PublishedRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCurrentRevision indicates an expected call of FindCurrentRevision.
func (mr *MockGraphRepositoryMockRecorder) FindCurrentRevision(ctx, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCurrentRevision", reflect.TypeOf((*MockGraphRepository)(nil).FindCurrentRevision), ctx, eventPublicID)
}

// FindObservationPointMappings mocks base method.
func (m *MockGraphRepository) FindObservationPointMappings(ctx context.Context, eventPublicID string) ([]domain.ObservationPointMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindObservationPointMappings", ctx, eventPublicID)
	ret0, _ := ret[0].([]domain.ObservationPointMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindObservationPointMappings indicates an expected call of FindObservationPointMappings.
func (mr *MockGraphRepositoryMockRecorder) FindObservationPointMappings(ctx, eventPublicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindObservationPointMappings", reflect.TypeOf((*MockGraphRepository)(nil).FindObservationPointMappings), ctx, eventPublicID)
}

// FindPlacements mocks base method.
func (m *MockGraphRepository) FindPlacements(ctx context.Context, graph domain.Graph) (domain.Placements, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPlacements", ctx, graph)
	ret0, _ := ret[0].(domain.Placements)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPlacements indicates an expected call of FindPlacements.
func (mr *MockGraphRepositoryMockRecorder) FindPlacements(ctx, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPlacements", reflect.TypeOf((*MockGraphRepository)(nil).FindPlacements), ctx, graph)
}

// Publish mocks base method.
func (m *MockGraphRepository) Publish(ctx context.Context, graph domain.Graph) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, graph)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockGraphRepositoryMockRecorder) Publish(ctx, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGraphRepository)(nil).Publish), ctx, graph)
}

// RemoveQrLocation mocks base method.
func (m *MockGraphRepository) RemoveQrLocation(ctx context.Context, graph domain.Graph, qrLocationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveQrLocation", ctx, graph, qrLocationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveQrLocation indicates an expected call of RemoveQrLocation.
func (mr *MockGraphRepositoryMockRecorder) RemoveQrLocation(ctx, graph, qrLocationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveQrLocation", reflect.TypeOf((*MockGraphRepository)(nil).RemoveQrLocation), ctx, graph, qrLocationID)
}

// Save mocks base method.
func (m *MockGraphRepository) Save(ctx context.Context, graph domain.Graph) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, graph)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGraphRepositoryMockRecorder) Save(ctx, graph any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGraphRepository)(nil).Save), ctx, graph)
}

// SaveObservationPointMapping mocks base method.
func (m *MockGraphRepository) SaveObservationPointMapping(ctx context.Context, graph domain.Graph, mapping domain.ObservationPointMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveObservationPointMapping", ctx, graph, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveObservationPointMapping indicates an expected call of SaveObservationPointMapping.
func (mr *MockGraphRepositoryMockRecorder) SaveObservationPointMapping(ctx, graph, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveObservationPointMapping", reflect.TypeOf((*MockGraphRepository)(nil).SaveObservationPointMapping), ctx, graph, mapping)
}

// UpdateQrLocation mocks base method.
func (m *MockGraphRepository) UpdateQrLocation(ctx context.Context, graph domain.Graph, location domain.QrLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQrLocation", ctx, graph, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQrLocation indicates an expected call of UpdateQrLocation.
func (mr *MockGraphRepositoryMockRecorder) UpdateQrLocation(ctx, graph, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQrLocation", reflect.TypeOf((*MockGraphRepository)(nil).UpdateQrLocation), ctx, graph, location)
}
